spring.application.name=demo.voiceApp
server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Transcript save location
transcript.folder=D:/transcripts

# Vosk models
vosk.model.en=C:/2025/software/vosk-model-en-in-0.5
vosk.model.hi=C:/2025/software/vosk-model-hi-0.22
#vosk.model.spk=C:/2025/software/vosk-model-spk-0.4

